// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The OpenVirtue Authors

using OpenVirtue.Formats.Tests.TestSupport;
using OpenVirtue.Formats.Wmp;
using OpenVirtue.Formats.Wrs;

namespace OpenVirtue.Formats.Tests.Wmp;

public class WmpMapTests
{
    private const string SampleMap =
        """
        #  This file was generated by WED v3.29
        #vertex	xpos ypos zpos index
        VERTEX 0.0 0.0 0.0;#0
        VERTEX 1.5 0.0 0.0;#1
        #region	name floor_hgt ceil_hgt
        REGION room 0.000 10.000;#0
        #wall	name vertex vertex region region offsx offsy index
        WALL w 0 1 0 -1 0.000 0.000;#0
        #thing
        THING torch 5.0 6.0 90.0 0;#1
        #actor name xpos ypos angle region index
        ACTOR guard 7.0 8.0 180.0 0;#2
        #player_start
        PLAYER_START 1.0 2.0 45.0 0;#3
        """;

    [Fact]
    public void Read_ParsesAllRecordTypes()
    {
        WmpMap map = WmpMap.Read(SampleMap);

        Assert.Equal(2, map.Vertices.Count);
        Assert.Equal(new WmpVertex(1.5f, 0f, 0f), map.Vertices[1]);
        Assert.Equal(new WmpRegion("room", 0f, 10f), Assert.Single(map.Regions));
        Assert.Equal(new WmpWall("w", 0, 1, 0, -1, 0f, 0f), Assert.Single(map.Walls));
        Assert.Equal(new WmpPlacement("torch", 5f, 6f, 90f, 0), Assert.Single(map.Things));
        Assert.Equal(new WmpPlacement("guard", 7f, 8f, 180f, 0), Assert.Single(map.Actors));
        Assert.Equal(new WmpPlayerStart(1f, 2f, 45f, 0), map.PlayerStart);
    }

    [Fact]
    public void Read_UnknownRecord_Throws()
    {
        Assert.Throws<InvalidDataException>(() => WmpMap.Read("FOO 1 2 3;"));
    }

    [Fact]
    public void Read_MissingField_Throws()
    {
        Assert.Throws<InvalidDataException>(() => WmpMap.Read("VERTEX 0.0 0.0;")); // needs 3 coords
    }

    /// <summary>
    /// Parses every real map (when present locally) and checks structural integrity:
    /// non-empty geometry, a player start, and walls that reference valid vertices.
    /// apathy.WMP's exact record counts are pinned as a regression guard. No-op without data.
    /// </summary>
    [Fact]
    public void Read_RealMaps_ParseWithValidGeometry()
    {
        IReadOnlyList<string> wrsFiles = ResearchData.WrsFiles();
        if (wrsFiles.Count == 0)
        {
            return; // no local game data — skip
        }

        int maps = 0;
        foreach (string path in wrsFiles)
        {
            WrsArchive archive = WrsArchive.ReadFile(path);
            foreach (WrsEntry entry in archive.Entries)
            {
                if (!entry.Name.EndsWith(".wmp", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                WmpMap map = WmpMap.Read(entry.GetData());

                Assert.NotEmpty(map.Vertices);
                Assert.NotEmpty(map.Regions);
                Assert.NotEmpty(map.Walls);
                Assert.NotNull(map.PlayerStart);

                foreach (WmpWall wall in map.Walls)
                {
                    Assert.InRange(wall.Vertex1, 0, map.Vertices.Count - 1);
                    Assert.InRange(wall.Vertex2, 0, map.Vertices.Count - 1);
                }

                if (entry.Name.Equals("apathy.WMP", StringComparison.OrdinalIgnoreCase))
                {
                    Assert.Equal(5192, map.Vertices.Count);
                    Assert.Equal(1073, map.Regions.Count);
                    Assert.Equal(5894, map.Walls.Count);
                    Assert.Equal(492, map.Things.Count);
                    Assert.Equal(138, map.Actors.Count);
                }

                maps++;
            }
        }

        Assert.True(maps > 0, "expected to parse at least one real map");
    }
}
